steps:
- name: maven:3.8.2-openjdk-16
  entrypoint: mvn
  args: ['test']
- name: maven:3.8.2-openjdk-16
  entrypoint: mvn
  args: ['package', "-Dmaven.test.skip=true"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/helloWorld", "--build-arg=JAR_FILE=target/helloWorld.jar", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helloWorld']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/helloWorld', 'frontend=gcr.io/$PROJECT_ID/helloWorld']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster-tcc'
options:
 logging: CLOUD_LOGGING_ONLY
